#!/bin/bash

_NAME=$(hostname)
_IP=$(hostname -I)
_OCTOFARM_VERSION=$(jq -r .version /home/pi/OctoFarm/package.json || echo "unknown")
_FARMPI_VERSION=$(cat /etc/farmpi_version || echo "unknown")

echo
echo "------------------------------------------------------------------------------"
echo "Access OctoFarm from a web browser on your network by navigating to any of:"
echo

for name in $_NAME;
do
    echo "    http://$name.local"
done
for ip in $_IP;
do
    if [[ $ip =~ .*:.* ]]
    then
        echo "    http://[$ip]"
    else
        echo "    http://$ip"
    fi
done

echo
echo "https is also available, with a self-signed certificate."
echo
echo "------------------------------------------------------------------------------"
echo "OctoFarm version : $_OCTOFARM_VERSION"
echo "FarmPi version    : $_FARMPI_VERSION"
echo "------------------------------------------------------------------------------"
echo
