#!/bin/bash

_NAME=$(hostname)
_IP=$(hostname -I)
_OCTOFARM_VERSION=$(jq -r .version /home/pi/OctoFarm/package.json || echo "unknown")
_FARMPI_VERSION=$(cat /etc/farmpi_version || echo "unknown")

echo
echo "------------------------------------------------------------------------------"
echo "Access OctoFarm from a web browser on your network by navigating to any of:"
echo

for name in $_NAME;
do
    echo "    http://$name.local"
done
for ip in $_IP;
do
    if [[ $ip =~ .*:.* ]]
    then
        echo "    http://[$ip]"
    else
        echo "    http://$ip"
    fi
done

echo
echo "https is also available, with a self-signed certificate."

if ! which lightdm 2>&1 >/dev/null;
then
    echo "------------------------------------------------------------------------------"
    echo "This image comes without a desktop environment installed because it's not "
    echo "required for running OctoFarm. If you want a desktop environment you can "
    echo "install it via"
    echo
    echo "    sudo /home/pi/scripts/install-desktop"
fi

echo "------------------------------------------------------------------------------"
echo "OctoFarm version : $_OCTOFARM_VERSION"
echo "FarmPi version    : $_FARMPI_VERSION"
echo "------------------------------------------------------------------------------"
echo
