layout: default
title: FarmPi
description: FarmPi Official Documentation
url: "https://farmpi.kevenaar.name"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
search.button: true
aux_links:
  "FarmPi GitHub":
    - "https://github.com/mkevenaar/FarmPi"
  "OctoFarm Home":
    - "https://octofarm.net"
  "OctoFarm Discord":
    - "https://discord.octofarm.net"
aux_links_new_tab: true

footer_content: "Copyright &copy; 2021-now Maurice Kevenaar. Distributed by an <a href=\"https://github.com/mkevenaar/FarmPi/blob/main/LICENSE\">GNU General Public License v3.0.</a>"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/mkevenaar/FarmPi"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

#ga_tracking: UA-202622681-1
ga_tracking: 365822581

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-last-modified-at
